apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: greenlight-api
  namespace: greenlight
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.127.0.0.1.nip.io`)
      kind: Rule
      services:
        - name: greenlight-api
          port: 4000
