apiVersion: v1
kind: ConfigMap
metadata:
  name: greenlight-migrations
  namespace: greenlight
data:
  000001_create_movies_table.up.sql: |
    CREATE TABLE IF NOT EXISTS movies (
        id bigserial PRIMARY KEY,
        created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
        title text NOT NULL,
        year integer NOT NULL,
        runtime integer NOT NULL,
        genres text[] NOT NULL,
        version integer NOT NULL DEFAULT 1
    );
  000002_add_movies_check_constraints.up.sql: |
    ALTER TABLE movies ADD CONSTRAINT movies_runtime_check CHECK (runtime >= 0);

    ALTER TABLE movies ADD CONSTRAINT movies_year_check CHECK (year BETWEEN 1888 AND date_part('year', now()));

    ALTER TABLE movies ADD CONSTRAINT genres_length_check CHECK (array_length(genres, 1) BETWEEN 1 AND 5);
  000003_add_movies_indexes.up.sql: |
    CREATE INDEX IF NOT EXISTS movies_title_idx ON movies USING GIN (to_tsvector('simple', title));
    CREATE INDEX IF NOT EXISTS movies_genres_idx ON movies USING GIN (genres);
  000004_create_users_table.up.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id bigserial PRIMARY KEY,
        created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
        name text NOT NULL,
        email citext UNIQUE NOT NULL,
        password_hash bytea NOT NULL,
        activated bool NOT NULL,
        version integer NOT NULL DEFAULT 1
    );
  000005_create_tokens_table.up.sql: |
    CREATE TABLE IF NOT EXISTS tokens (
        hash bytea PRIMARY KEY,
        user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
        expiry timestamp(0) with time zone NOT NULL,
        scope text NOT NULL
    );
  000006_add_permissions.up.sql: |
    CREATE TABLE IF NOT EXISTS permissions (
        id bigserial PRIMARY KEY,
        code text NOT NULL
    );

    CREATE TABLE IF NOT EXISTS users_permissions (
        user_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
        permission_id bigint NOT NULL REFERENCES permissions ON DELETE CASCADE,
        PRIMARY KEY (user_id, permission_id)
    );

    INSERT INTO permissions (code)
    VALUES
        ('movies:read'),
        ('movies:write');
